name: Merge pull request

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  validate-deployment:
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim
    steps:      
      - name: 'Checkout source code'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Authenticate using SFDX_AUTH_URL'
        run: | 
          echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u

      - name: 'Validate (Check-Only)'
        run: |
          sf project deploy start -d force-app/ --check-only -w 30 > result.txt
          export DEPLOY_ID=$(grep -oP '(?<=0Af)[a-zA-Z0-9]{15}' result.txt)
          echo "DEPLOY_ID=$DEPLOY_ID" >> $GITHUB_ENV

      - name: 'Quick Deploy'
        run: |
          sf project deploy quick --job-id ${{ env.DEPLOY_ID }} -w 10

